config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/index'

  root 'pericopes#index'

  namespace :admin do
    root 'application#index'
    resources :biblebooks do
      resources :chapters, except: [:index]
    end
    resources :users, except: [:destroy]
  end

  devise_for :users

  resources :studynotes
  resources :pericopes, except: [:create, :update]

  get 'profile', to: 'users#show'
end

app/models/studynote.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: studynotes
#
#  id         :integer          not null, primary key
#  note       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  title      :string
#  author_id  :integer
#

# Models a Studynote, the main Object for this application
class Studynote < ActiveRecord::Base
  has_many :pericopes, inverse_of: :studynote, dependent: :destroy
  # accepts_nested_attributes_for :pericopes,
  #                               allow_destroy: true,
  #                               reject_if: :all_blank
  accepts_nested_attributes_for :pericopes,
                                allow_destroy: true,
                                reject_if: RejectDeeplyNested.blank?

  has_many :biblebooks, through: :pericopes
  has_many :roles, dependent: :delete_all

  belongs_to :author, class_name: 'User'

  delegate :username, to: :author, prefix: true
  delegate :email, to: :author, prefix: true

  validates :note,  presence: true
  validates :title, presence: true
end

app/controllers/studynotes_controller.rb
# frozen_string_literal: true

# Controller for Studynotes (the main object in the application)
# Handling the typical CRUD actions
class StudynotesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_studynote, only: %i[show edit update destroy]

  attr_reader :studynote

  def index
    studynote = Studynote.all.order(:title)
    locals studynote: studynote
  end

  def show
    locals studynote: studynote
  end

  def new
    index     = params[:index].to_i
    studynote = Studynote.new
    authorize studynote, :create?
    studynote.pericopes.build
    locals studynote: studynote, index: index
  end

  def create
    studynote        = Studynote.new(studynote_params)
    studynote.author = current_user
    save_studynote(studynote)
  end

  def edit
    authorize studynote, :update?
    locals studynote: studynote
  end

  def update
    authorize studynote, :update?
    update_studynote
  end

  def destroy
    authorize studynote, :destroy?
    studynote.destroy
    flash[:notice] = t('activerecord.messages.deleted', model: 'bijbelstudie')
    redirect_to pericopes_path
  end

  private

  def update_studynote
    name = Studynote.model_name.human
    if studynote.update(studynote_params)
      flash[:notice] = t(:item_updated, item: name)
      redirect_to studynote
    else
      flash.now[:alert] = t(:item_not_updated, item: name)
      locals :edit, studynote: studynote
    end
  end

  def save_studynote(studynote)
    name = Studynote.model_name.human
    if studynote.save && !studynote.pericopes.empty?
      # TODO, the second condiotion is a hack, needed because the standard rails validation does not work
      # on nested attributes.
      flash[:notice] = t(:item_created, item: name)
      redirect_to studynote
    else
      flash.now[:alert] = t(:item_not_created, item: name)
      locals :edit, studynote: studynote
    end
  end

  def studynote_params
    params.require(:studynote).permit(:id,
                                      :title,
                                      :note,
                                      pericopes_attributes:
                                      %i[id name _destroy])
  end

  def set_studynote
    @studynote = Studynote.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = t(:studynote_not_found)
    redirect_to studynotes_path
  end
end

app/views/studynotes/_form.html.haml
= simple_form_for studynote, wrapper: :vertical_input_group, validate_pericope_order: true do |f|
  #pericopes
    - pnum = 1
    = f.simple_fields_for :pericopes, wrapper: :vertical_input_group do |pericope|
      = render 'pericope_fields', f: pericope, pnum: pnum
      - pnum += 1
    .links
      = link_to_add_association t('add_pericope'), f, :pericopes, class: 'new btn-xs', id: 'add_pericope'
  = f.input :title
  = f.input :note, as: :trix_editor, id: 'editor', class: 'editor'
  = f.button :submit, class: "btn-primary", id: 'submit_form'

app/views/studynotes/_pericope_fields.html.haml
.nested-fields
  .input-group
    = f.input :name,
              label: "#{ t('simple_form.labels.pericopes.name') } #{local_assigns[:pnum]}",
              placeholder: 'Genesis 1:1-3:21',
              autofocus: true,
              class: 'input-group horizontal_form'
    %span(class = 'input-group-btn')
      = link_to_remove_association '', f, class: 'delete', style: 'margin-bottom:-9px', id: "delete_pericope_#{local_assigns[:pnum]}"

app/views/studynotes/edit.html.haml
%header
  %h1 Edit Studynote
= render "form", studynote: studynote

app/views/studynotes/index.html.haml
%header
  %h1
    = t('activerecord.models.studynote', count: 2)
  %ul.actions
    = link_to t(:new_studynote), new_studynote_path, class: "new"
#studynotes
  %table#studynotes
    - studynote.each do |studynote|
      %tr
        %td= link_to studynote.title, studynote
        %td
          %table#pericopes
            - studynote.pericopes.each do |pericope|
              %tr
                %td= pericope.name

app/views/studynotes/new.html.haml
%header
  %h1
    = t(:new_studynote)
= render "form", studynote: studynote

app/views/studynotes/show.html.haml
#studynote
  - title(@studynote.note, t('activerecord.models.studynote', count: 2))
  %header
    #title
      %h1= studynote.title
    %ul.actions
      - if policy(studynote).update?
        %li= link_to t(:edit_item, item: Studynote.model_name.human), edit_studynote_path(studynote), class: "edit"
      - if policy(@studynote).destroy?
        %li= link_to t(:delete_item, item: Studynote.model_name.human), studynote_path(studynote),
          method: :delete,
          data: { confirm: t(:sure_to_delete_studynote) },
          class: "delete"
  %header
    %p
    #pericope
      = studynote.pericopes.collect(&:name).join(' | ')
    #studynote_note
      %p= simple_format studynote.note
  %table#attributes
    %tr
      %th
        = t('author')
      %td
        #author
          = studynote.author_username
    %tr
      %th
        = t('created')
      %td
        #created_at
          = timeago(studynote.created_at)
        -#= t('ago')
  = link_to t(:new_studynote), new_studynote_path, class: "new"