config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/index'

  root 'pericopes#index'

  namespace :admin do
    root 'application#index'
    resources :biblebooks do
      resources :chapters, except: [:index]
    end
    resources :users, except: [:destroy]
  end

  devise_for :users

  resources :studynotes
  resources :pericopes, except: [:create, :update]

  get 'profile', to: 'users#show'
end

app/models/biblebook.rb
# frozen_string_literal: true

#
# == Schema Information
#
# Table name: biblebooks
#
#  id           :integer          not null, primary key
#  name         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  booksequence :integer
#  testament    :string
#  abbreviation :string
#

# Models one Biblebook
# Has utitlity methods to help validate biblebooks
class Biblebook < ActiveRecord::Base
  validates :name, presence: true

  has_many :chapters, dependent: :delete_all
  has_many :pericopes
  has_many :studynotes, through: :pericopes
  has_one :biblebook_category

  default_scope { order('booksequence ASC') }
  scope :find_by_full_name, -> (name) { where(name: name) }
  scope :find_by_abbreviation, -> (abbreviation) { where(Biblebook.arel_table[:abbreviation].matches(abbreviation)) }
  scope :find_names_by_like, -> (name) { where(Biblebook.arel_table[:name].matches("%#{name.slice(0, 5)}%")) }

  # Returns the number of chapters in this biblebook
  # #return [Integer]
  def nr_of_chapters
    Chapter.where(biblebook_id: id).count
  end
  alias size nr_of_chapters

  # A chapter is valid if it exists in the biblebook,
  # so it must be positive and less than the number of chapters
  # @param [Integer] chapter number
  # @return [Boolean]
  # :reek:FeatureEnvy - seen from a caller, this is the place where the method belongs
  def chapter_valid?(chapter)
    chapter.positive? && chapter <= nr_of_chapters
  end

  # Returns the name of a Biblebook if it can be found by any kind of name
  # @param [String]
  # - complete name, e.g. Genesis
  # - official abbreviation, e.g. gen
  # - fitting abbreviation, e.g. Gene

  # @return [Array]
  # - empty if not found
  # - one element if one found
  # - multiple elements if multiple found
  # :reek:DuplicateMethodCall - don't know how to solve that right now
  def self.possible_book_names(name)
    biblebook = find_by_full_name(name)
    unless exists?(biblebook)
      biblebook = find_by_abbreviation(name)
      unless exists?(biblebook)
        biblebook = find_names_by_like(name)
      end
    end

    biblebook.map(&:name).uniq
  end

  private

  # Tells if this biblebook exists
  # @param [Biblebook]
  # @return [Boolean]
  def self.exists?(biblebook)
    !biblebook.empty?
  end
end

app/controllers/admin/biblebooks_controller.rb
# frozen_string_literal: true

module Admin
  # Controller for Biblebooks
  # Handling the typical CRUD actions
  class BiblebooksController < Admin::ApplicationController
    before_action :set_biblebook, only: %i[show edit update destroy]

    attr_reader :biblebook

    def index
      biblebook = Biblebook.all
      locals biblebook: biblebook
    end

    def show; end

    def new
      biblebook = Biblebook.new
      locals :new,  biblebook: biblebook
    end

    def create
      biblebook = Biblebook.new(biblebook_params)
      save_biblebook(biblebook)
    end

    def edit; end

    def update
      name = Biblebook.model_name.human
      update_biblebook(name)
    end

    def destroy
      biblebook.destroy
      flash[:notice] = t(:biblebook_deleted)
      redirect_to admin_biblebooks_path
    end

    private

    def update_biblebook(name)
      if biblebook.update(biblebook_params)
        flash[:notice] = t(:item_updated,
                           item: name)
        redirect_to [:admin, biblebook]
      else
        flash.now[:alert] = t(:item_not_updated,
                              item: name)
        render 'edit'
      end
    end

    def save_biblebook(biblebook)
      name = Biblebook.model_name.human
      if biblebook.save
        flash[:notice] = t(:item_created,
                           item: name)
        redirect_to [:admin, biblebook]
      else
        flash.now[:alert] = t(:item_not_created,
                              item: name)
        locals :new, biblebook: biblebook

      end
    end

    def biblebook_params
      params.require(:biblebook).permit(:name, :booksequence, :testament)
    end

    def set_biblebook
      @biblebook = Biblebook.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = t(:biblebook_not_found)
      redirect_to admin_biblebooks_path
    end
  end
end

app/views/admin/biblebooks/_form.html.haml
= simple_form_for([:admin, biblebook]) do |f|
  = f.input  :name
  = f.input  :booksequence
  = f.input  :testament
  = f.button :submit, class: 'btn-primary'

app/views/admin/biblebooks/edit.html.haml
%header
  %h1= t(:edit_item, item: Biblebook.model_name.human)
= render "form", biblebook: @biblebook

app/views/admin/biblebooks/index.html.haml
%header
  %h1= Biblebook.model_name.human(count: 2).capitalize
  %ul.actions
    %li= link_to t(:new_biblebook), new_admin_biblebook_path, class: 'new'
#biblebooks
  - biblebook.each do |biblebook|
    %h2
      = link_to "#{biblebook.booksequence} - #{biblebook.name} - #{biblebook.testament}", |
        [:admin, biblebook]                                                               |

app/views/admin/biblebooks/new.html.haml
%header
  %h1= t(:new_biblebook)
= render 'form', biblebook: biblebook

app/views/admin/biblebooks/show.html.haml
- title(@biblebook.name, Biblebook.model_name.human(count: 2).capitalize)
%header
  %h1= @biblebook.name
  %ul.actions
    %li= link_to t(:edit_item, item: Biblebook.model_name.human), edit_admin_biblebook_path(@biblebook), class: 'edit'
    %li= link_to t(:delete_item, item: Biblebook.model_name.human), admin_biblebook_path(@biblebook), |
        method: :delete,                                                                             |
        data: { confirm: t(:sure_to_delete, item: Biblebook.model_name.human) },                     |
        class: 'delete'                                                                              |
%header
  %h2= t('activerecord.models.chapter', count: 1).capitalize
  %ul.actions
    %li= link_to t(:add_chapter), new_admin_biblebook_chapter_path(@biblebook), |
        class: 'new'                                                           |
%ul#chapters
  - @biblebook.chapters.each do |chapter|
    %li
      = link_to chapter.chapter_number, [:admin, @biblebook, chapter]
      = " - #{chapter.description}" if chapter.description.present?