config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/index'

  root 'pericopes#index'

  namespace :admin do
    root 'application#index'
    resources :biblebooks do
      resources :chapters, except: [:index]
    end
    resources :users, except: [:destroy]
  end

  devise_for :users

  resources :studynotes
  resources :pericopes, except: [:create, :update]

  get 'profile', to: 'users#show'
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  admin                  :boolean          default(FALSE)
#  username               :string
#

# Models a User, so Devise can use it
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_uniqueness_of :email, allow_blank: true, if: :email_changed?

  # Creates a nice user string to be displayed
  def to_s
    "#{email} (#{admin? ? 'Admin' : 'User'})"
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  # Controller for Users
  # Handling the typical CRUD actions
  class UsersController < Admin::ApplicationController
    before_action :set_user, only: %i[show edit update destroy]

    attr_reader :user

    def index
      users = User.order(:email)
      locals users: users
    end

    def show
      locals user: user
    end

    def new
      user = User.new
      locals user: user
    end

    def create
      user       = User.new(user_params)
      user.admin = params[:user][:admin] if current_user.admin?
      save_user(user)
    end

    def edit
      locals user: user
    end

    def update
      user = params[:user]
      user.delete(:password) if user[:password].blank?
      update_user
    end

    private

    def save_user(user)
      if user.save
        flash[:notice] = t('activerecord.messages.created')
        redirect_to admin_users_path
      else
        flash.now[:alert] = t('activerecord.messages.notcreated')
        locals :new, user: user
      end
    end

    def update_user
      if @user.update(user_params)
        set_admin
        flash[:notice] = t('activerecord.attributes.user.messages.updated')
        redirect_to admin_users_path
      else
        flash.now[:alert] =
          t('activerecord.attributes.user.messages.notupdated')
        locals :edit, user: user
      end
    end

    def set_admin
      return unless current_user.admin?
      @user.admin = params[:user][:admin]
      @user.save
    end

    def user_params
      params.require(:user).permit(:email, :password, :username)
    end

    def set_user
      @user = User.find(params[:id])
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Controller for Users
# Handling the typical CRUD actions
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index; end

  def show
    render 'devise/registrations/_form', user: @user
  end

  private

  def set_user
    @user = current_user
  end
end

app/views/admin/users/_form.html.haml
= simple_form_for [:admin, user] do |f|
  = f.input :username
  = f.input :email
  = f.input :password
  = f.input :admin, label: t("activerecord.attributes.user.is_admin")
  = f.button :submit, class: "btn btn-primary"

app/views/admin/users/edit.html.haml
%header
  %h1 Edit User
= render "form", user: user

app/views/admin/users/index.html.haml
%header
  %h1 Users
  %ul.actions
    %li
      = link_to "New User", new_admin_user_path, class: "new"
%table#users.sortable
  %tr
    %th user
    %th #logins
    %th last login date
    %th #studies
  - users.each do |user|
    %tr
      %td#username= link_to user, [:admin, user]
      %td#signin_count= user.sign_in_count
      %td{:id => "last_sign_in\""}= user.last_sign_in_at
      %td{:id => "studynote count"}= Studynote.where(author_id: user).count

app/views/admin/users/new.html.haml
%header
  %h1 New User
= render "form", user: user

app/views/admin/users/show.html.haml
%header
  %h1= user
  %ul.actions
    %li
      = link_to "Edit User", [:edit, :admin, user], class: "edit"