config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/index'

  root 'pericopes#index'

  namespace :admin do
    root 'application#index'
    resources :biblebooks do
      resources :chapters, except: [:index]
    end
    resources :users, except: [:destroy]
  end

  devise_for :users

  resources :studynotes
  resources :pericopes, except: [:create, :update]

  get 'profile', to: 'users#show'
end

app/models/chapter.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: chapters
#
#  id             :integer          not null, primary key
#  chapter_number :integer
#  description    :string
#  biblebook_id   :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  nrofverses     :integer
#

# Models a Chapter within a Biblebook
class Chapter < ActiveRecord::Base
  belongs_to :biblebook

  validates :chapter_number, presence: true

  # Spaceship to help Comparable methods
  def <=> (other)
    self.chapter_number <=> other.chapter_number
  end
end

app/controllers/admin/chapters_controller.rb
# frozen_string_literal: true

module Admin
  # Controller for Chapters
  # Handling the typical CRUD actions
  class ChaptersController < Admin::ApplicationController
    before_action :set_biblebook
    before_action :set_chapter, only: %i[show edit update destroy]

    attr_reader :chapter, :biblebook

    def show
      locals biblebook: biblebook, chapter: chapter
    end

    def new
      chapter = biblebook.chapters.build
      locals chapter: chapter
    end

    def create
      chapter = biblebook.chapters.build(chapter_params)
      save_chapter(chapter)
    end

    def edit
      locals biblebook: biblebook, chapter: chapter
    end

    def update
      name = Chapter.model_name.human
      if chapter.update(chapter_params)
        flash[:notice] = t(:item_updated, item: name)
        redirect_to [:admin, biblebook, chapter]
      else
        flash.now[:alert] = t(:item_not_updated, item: name)
        render 'edit'
      end
    end

    def destroy
      chapter.destroy
      flash[:notice] = t(:item_deleted, item: Chapter.model_name.human)
      redirect_to [:admin, biblebook]
    end

    private

    def save_chapter(chapter)
      name = Chapter.model_name.human
      if chapter.save
        flash[:notice] = t(:item_created, item: name)
        redirect_to [:admin, biblebook, chapter]
      else
        flash.now[:alert] = t(:item_not_created, item: name)
        locals :new, biblebook: biblebook, chapter: chapter
      end
    end

    def chapter_params
      params.require(:chapter).permit(:chapter_number,
                                      :description,
                                      :nr_of_verses)
    end

    def set_biblebook
      @biblebook = Biblebook.find(params[:biblebook_id])
    end

    def set_chapter
      @chapter = biblebook.chapters.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = t(:chapter_not_found)
      redirect_to admin_biblebook_chapters_path
    end
  end
end

app/views/admin/chapters/_form.html.haml
= simple_form_for([:admin, biblebook, chapter]) do |f|
  = f.input :chapter_number
  = f.input :description
  = f.input :nrofverses
  = f.button :submit, class: "btn-primary"

app/views/admin/chapters/edit.html.haml
%header
  %h1 Edit Chapter
= render "form", chapter: chapter, biblebook: biblebook

app/views/admin/chapters/new.html.haml
%header
  %h1
    = "#{t(:add_chapter)} in #{@biblebook.name}"
= render "form", biblebook: @biblebook, chapter: chapter

app/views/admin/chapters/show.html.haml
#chapter
  %header
    %h1= biblebook.name
    %ul.actions
      %li
        = link_to t(:delete_item, item: Chapter.model_name.human), [:admin, biblebook, chapter], |
          method: :delete,                                                                         |
          data: { confirm: t(:sure_to_delete, item: Chapter.model_name.human) },                   |
          class: "delete"                                                                          |
      %li= link_to t(:edit_item, item: Chapter.model_name.human), edit_admin_biblebook_chapter_path(biblebook, chapter), class: "edit"
  %header
    %h2= "#{t('activerecord.models.chapter', count: 1).capitalize} #{chapter.chapter_number}"
  = simple_format(chapter.description)
  = chapter.nrofverses